# Name of workflow
name: Build Check

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - main

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      # Install dependencies
      - name: Install dependencies
        run: npm install
        
      # Run build
      - name: Build project
        run: npm run build
